### ISSUE TITLE
About labeled_tree_label  function   problem

### ISSUE THREAD

**Issue by xtyi1997** [gear/graph-homomorphism-network#3]
Traceback (most recent call last):
  File "./models/mlp.py", line 94, in <module>
    for g in tqdm(graphs, desc="Hom")]
  File "./models/mlp.py", line 94, in <listcomp>
    for g in tqdm(graphs, desc="Hom")]
  File "/home/yxt/graph-homomorphism-network/src/ghc/homomorphism.py", line 118, in labeled_tree_profile
    hom_list = [hom_tree_labeled(t, G, node_tags) for t in t_list]
  File "/home/yxt/graph-homomorphism-network/src/ghc/homomorphism.py", line 118, in <listcomp>
    hom_list = [hom_tree_labeled(t, G, node_tags) for t in t_list]
  File "/home/yxt/graph-homomorphism-network/src/ghc/homomorphism.py", line 42, in hom_tree_labeled
    hom_r = rec(0, -1)
  File "/home/yxt/graph-homomorphism-network/src/ghc/homomorphism.py", line 39, in rec
    aux = [np.sum(hom_y[:,list(G.neighbors(a))]) for a in G.nodes()]
  File "/home/yxt/graph-homomorphism-network/src/ghc/homomorphism.py", line 39, in <listcomp>
    aux = [np.sum(hom_y[:,list(G.neighbors(a))]) for a in G.nodes()]
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
Hom:   0%|                                              | 0/188 [00:00<?, ?it/s]

There was a bug in this，Could you give a help at your convenience

**Comment by gear** [comment]
Could you provide more information? Such as which dataset are you running on? It seems you are trying to compute labeled homomorphism, have you checked the feature shapes?

**Comment by xtyi1997** [comment]
> Could you provide more information? Such as which dataset are you running on? It seems you are trying to compute labeled homomorphism, have you checked the feature shapes?

yea. 
my dataset == "mutag"  
size ==6
the dataset is well done.
I check the feature shape of input X.  I find it is one dimension. 
I tray to fixed it ,but failed 
![image](https://user-images.githubusercontent.com/28750869/112941301-edf3d500-9160-11eb-905b-f3bf595b197d.png)

**Comment by gear** [comment]
@xtyi1997 Thank you! It was my mistake in the file models/mlp.py (line 93 to 94). I updated the code.
If you want to fix it yourself, you just need to change the 93-94 lines to the following:

```python
homX = [hom_func(g, size=args.hom_size, density=False, node_tags=X[i])\
                for i, g in enumerate(tqdm(graphs, desc="Hom"))]
```

The old version passed the whole node tags array, which has 188 np.arrays of various sizes. We only pass the corresponding feature of the input graph here. The old (wrong) code:

```python
homX = [hom_func(g, size=args.hom_size, density=False, node_tags=X)\  # Passing X here is wrong.
                for g in tqdm(graphs, desc="Hom")] 
```

**Comment by xtyi1997** [comment]
Thank you for your answer！
